---
abstract: 'Patch package with a set of patches'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Capture::Tiny: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::Exception: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Patch
requires:
  Log::Any: 0
  Monkey::Patch::Action: 0.01
  SHARYANTO::Array::Util: 0
  SHARYANTO::Package::Util: 0
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Module-Patch
  homepage: https://metacpan.org/release/Module-Patch
  repository: git://github.com/sharyanto/perl-Module-Patch.git
version: 0.18
